name: build and push GroupManagerBot image to ghcr

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jonatan1609/group-manager-bot

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      id: prep
      run: |
        echo ::set-output name=version::${GITHUB_REF##*/}-$(git rev-parse --short HEAD)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.version }}
        push: true
